name: gen-jira
description: "Jira ticket implementation general"
script: "bin/generals/gen-jira.sh"
timeout_seconds: 5400

cc_plugin:
  name: sunday
  path: "plugins/sunday"

subscribes:
  - jira.ticket.assigned
  - jira.ticket.updated

schedules: []
