# yaml-language-server: $schema=../schemas/envoy.schema.json
slack:
  bot_token_env: "SLACK_BOT_TOKEN"
  default_channel: "dev-eddy"

intervals:
  outbound_seconds: 5
  thread_check_seconds: 30
  loop_tick_seconds: 5
  channel_check_seconds: 30
  conversation_check_seconds: 15
  conversation_ttl_seconds: 3600
